### ISSUE TITLE
Tool Update Permission - 'specifed list of users'

### ISSUE THREAD

**Issue by zagorGit** [bio-tools/biotoolsDocs#33]
Update tool - Permissions offers options:
Make this resource editable by me only
Make this resource editable by anyone
Make this resource editable for a specifed list of users

Could we create our own 'specifed list of users' (also maybe change this to 'specified list of users') or only predefined persons (not sure how) are allowed? E.g. I would like to add my collaborators to be able to update descriptions of our tools, however i can only add direct ELIXIR employees.

**Comment by hansioan** [comment]
@zagorGit 
You can use the "Make this resource editable for a specifed list of users" and type the users you would like to add.
If by "specifed list of users" you are refering to a sort of predefined "group" then that is not possible at the moment.
But if you have many tools and want to add the same list of users to all those many tools, then you can probably do it faster via the JSON tab in the tool editor.

Suppose you have 3 users  (user1, user2 and user3) to whom you wish to give permissions, then the JSON representation of the permissions is:

```
 "editPermission": {
    "type": "group",
    "authors": [
      "user1",
      "user2",
      "user3"
    ]
  }
```

You can have this ready and just paste in the JSON tab, see below an example of a minimal tool annotation + permissions for user1, user2 and user3:
```
{
  "name": "Multi_user_tool",
  "description": "Tool edited by multiple people",
  "homepage": "http://example.com",
  "editPermission": {
    "type": "group",
    "authors": [
      "user1",
      "user2",
      "user3"
    ]
  }
}
```

The owner field won't appear when you're adding a tool, but will appear when you're updating a tool.
Also remember to have a valid JSON structure, don't forget a comma before your `editPermission:{` object and also after if it's not the last element. 
Hope this helps
