### ISSUE TITLE
Update API docs for consistency

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsDocs#8]
Ensure correct / consistent use e.g. attribute descriptions, restrictions / facets etc. in 
* current API docs (http://biotools.readthedocs.io/en/latest/api_reference.html) 
* next-gen API docs (http://biotools.readthedocs.io/en/latest/api_reference_dev.html)
* JSON attributes description (http://biotools.readthedocs.io/en/latest/api_attribute_model_dev.html)
* Curators Guide (http://biotools.readthedocs.io/en/latest/curators_guide.html)

Jon and @ekry to work on this together : the first step being to align biotoolsSchema and JSON model internally, then fix docs above.

**Comment by 0xaf1f** [comment]
Is this why some examples like http://biotools.readthedocs.io/en/latest/api_reference.html#id5 fail?

```
Example

curl -X GET "https://bio.tools/api/t/signalp/version/"
```


```
$ curl -X GET "https://bio.tools/api/t/signalp/version/"
<h1>Not Found</h1><p>The requested URL /api/t/signalp/version/ was not found on this server.</p>
```
